---
name: Format Check and Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up tools
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install clang-format==20.1.8 findent

    - name: Run format script
      run: python3 tools/format_all.py

    - name: Check for formatting violations
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Code formatting issue detected! Please run 'python3 tools/format_all.py' locally and push."
          git diff
          exit 1
        fi
